name: CI with matrix
on: 
  push:

jobs:
 build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name_image: cv-duilder
            target: builder
          - name_image: cv-final
            target: final

    steps:
      - name: Check out Project
        uses: actions/checkout@v3

      - name: Build all
        uses: ./.github/actions/
        with:
          context: .
          file: ./Dockerfile
          push: false
          image: ${{matrix.name_image}}
          tags: ${{matrix.name_image}}:${{inputs.tag != '' && inputs.tag || github.ref_name}}
          target: ${{matrix.target}}
